### ISSUE TITLE
can we have an option to for ssl to verify none?

### ISSUE THREAD

**Issue by holajoyce** [kawasakitoshiya/fluent-plugin-out-http-ext#14]
https.verify_mode = OpenSSL::SSL::VERIFY_NONE

**Comment by toshitanian** [comment]
this PR will do that.
https://github.com/kawasakitoshiya/fluent-plugin-out-http-ext/pull/4/files

will merge and bump version.

**Comment by toshitanian** [comment]
@holajoyce 

fixed in #15 .
this option is available with version 0.1.8.

https://rubygems.org/gems/fluent-plugin-out-http-ext
