### ISSUE TITLE
Formatter Support

### ISSUE THREAD

**Issue by jezeniel** [kawasakitoshiya/fluent-plugin-out-http-ext#21]
Is there a chance that we can add formatter support? I can create a PR for this one but who will handle the building of the new version?

**Comment by toshitanian** [comment]
@jezeniel Here is a original repo. Please make a pull request to it if it meets your requirements. https://github.com/ento/fluent-plugin-out-http

I'm planning to make a patch that applies our diffs to this repo.

**Comment by jezeniel** [comment]
https://github.com/ento/fluent-plugin-out-http/pull/26

if the above is not merged for a week can i PR it here?

**Comment by toshitanian** [comment]
@jezeniel 
Okay. go ahead then. I can push new version.

**Comment by jezeniel** [comment]
@toshitanian any updates? I created a pull request #22

**Comment by toshitanian** [comment]
@jezeniel  Just release v0.1.10 that includes your changes ;)
https://rubygems.org/gems/fluent-plugin-out-http-ext/versions/0.1.10
